server:
  servlet:
    context-path: /auth
  port: 8203

spring:
  data:
    mongodb:
      database: RMART_STORE_DEV
      host: localhost
      port: 27017

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
