server:
  port: 8201

spring:
  data:
    mongodb:
      database: RMART_STORE_DEV
      host: localhost
      port: 27017

  application:
    name: order

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/